server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_route
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**

        - id: payment_route2
          uri: lb://CLOUD-PAYMENT-SERVICE
          filters:
            - AddRequestHeader=X-Request-Foo, Bar
          predicates:
            - Path=/payment/lb/**
            - After=2020-05-27T17:27:41.632+08:00[Asia/Shanghai]
#            - Cookie=username,yk
#            - Header=X-Request-Id, \d+ # 请求头包含X-Request-Id属性，并且值为整数 curl http://localhost:9527/payment/lb --cookie "username=yk" -H "X-Request-Id:34"

eureka:
  client:
    # true表示向注册中心注册自己
    register-with-eureka: true
    # 是否从eureka server抓取已有的注册信息，默认为true。集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    hostname: cloud-gateway-service