server:
  port: 80

eureka:
  client:
    # true表示向注册中心注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

ribbon:
  # 设置超时时间，默认为1秒，5000表示5秒
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    com.yk.springcloud.service.PaymentFeignService: debug